import type {
  Credential,
  ProjectDependency,
  ProgressEntry,
  Project,
  ProjectTypeInfo,
  ProjectComment,
  Reminder,
  ReminderSchedule,
  User,
} from "./types";

export const users: User[] = [
  {
    id: 1,
    name: "Harir",
    email: "harir@jayasurvei.co.id",
    avatarUrl: null,
    role: "Project Manager"
  },
  {
    id: 2,
    name: "Rika",
    email: "rika@jayasurvei.co.id",
    avatarUrl: null,
    role: "Project Manager"
  },
  {
    id: 3,
    name: "Nurdiyansah",
    email: "nurdiyansah@jayasurvei.co.id",
    avatarUrl: null,
    role: "Project Manager"
  },
  {
    id: 6,
    name: "Admin Uji",
    email: "admin@jayasurvei.co.id",
    avatarUrl: null,
    role: "Administrator"
  }
];

export const currentUser: User = users[0];

export const projectTypes: ProjectTypeInfo[] = [
  { code: "Penjualan", label: "Penjualan", description: "Pengadaan alat dan solusi ke klien.", sortOrder: 0 },
  { code: "Jasa", label: "Jasa", description: "Pekerjaan survei dan layanan lapangan.", sortOrder: 1 },
  { code: "Training", label: "Training", description: "Pelatihan dan transfer pengetahuan.", sortOrder: 2 },
  { code: "Riset", label: "Riset", description: "Kajian pasar dan pengembangan internal.", sortOrder: 3 },
];

export const projects: Project[] = [
  {
    id: 1,
    name: "Riset Carbon Stock",
    description: "Riset mengenai penggunaan SLAM LiDAR Untuk perhitungan Carbon Stock",
    type: "Riset",
    status: "Berjalan",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "Undip",
    locationCity: "Semarang",
    locationProvince: "Jawa Tengah",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: null,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-30",
    deadline: "2026-09-03",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 2,
    name: "MOU ITERA",
    description: "MOU Terkait riset dan training dengan Teknik Geomatik ITERA",
    type: "Riset",
    status: "Berjalan",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "ITERA",
    locationCity: "Lampung",
    locationProvince: "Lampung",
    clientName: "Ulin",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: null,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-09-07",
    deadline: "2026-09-07",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 3,
    name: "Batas Lahan dan Situasi ",
    description: "Jasa Pengukuran Topografi Batas Lahan dan Situasi Area Komplek Pertamina Zona 4 Prabumulih",
    type: "Jasa",
    status: "Berjalan",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "PT Pertamina Zona 4 Prabumulih",
    locationCity: "Prabumulih",
    locationProvince: "Sumatera Selatan",
    clientName: "Ilham habibie",
    clientEmail: "",
    clientPhone: "085210207730",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 152100000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-07-06",
    deadline: "2026-09-06",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 4,
    name: "Topografi LiDAR PLTA  Medan Aceh",
    description: "Topografi Lidar PLTA 440 ha dan 846Ha ",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Saris Geoterra",
    locationCity: "Medan, Aceh",
    locationProvince: "Sumatera Utara",
    clientName: "Saris",
    clientEmail: "",
    clientPhone: "085378676656",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 469021500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 5,
    name: "Topografi LiDAR 9000 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Sriwijaya Tansri Energi",
    locationCity: "Muara Enim",
    locationProvince: "Sumatera Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 2205450000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 6,
    name: "Topografi LiDAR 4500 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Sriwijaya Tansri Energi",
    locationCity: "Muara Enim",
    locationProvince: "Sumatera Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 797850000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 7,
    name: "Topografi LIDAR 2762HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Geoffrey Asia Energy",
    locationCity: "Ketapang, ",
    locationProvince: "Kalimantan Barat",
    clientName: "Candra",
    clientEmail: "",
    clientPhone: "081253652680",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 373735000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 8,
    name: "Topografi LiDAR 1500Ha",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "IBIP",
    locationCity: "Bintan",
    locationProvince: "Kepri",
    clientName: "Zuria Hidayat",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 327616500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 9,
    name: "Topografi LiDAR 7000Ha",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Bhaktiputra Persada Nusantara",
    locationCity: "Morowali Utara",
    locationProvince: "Sulawesi Tengah",
    clientName: "Masdar",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 973969500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 10,
    name: "Topografi Foto Udara",
    description: "Topografi Foto Udara",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Trimata Coal Perkasa",
    locationCity: "Musi Banyuasin",
    locationProvince: "Sumatera Selatan",
    clientName: "Karta Sudarso",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 1131700500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 11,
    name: "Survei GPR 7 KM",
    description: "Survei GPR",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Sufyan",
    locationCity: "Makassar",
    locationProvince: "Sulawesi Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "081356001212",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 140000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 12,
    name: "Survei Stock Opname",
    description: "Survei Stock Opname",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Carsurin",
    locationCity: "Pomala",
    locationProvince: "Sulawesi Tenggara",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 50000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 13,
    name: "Topografi LiDAR 1500 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Anugerah Jaya Buana",
    locationCity: "LuwuTimur",
    locationProvince: "Sulawesi Selatan",
    clientName: "Masdar",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 420523400,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 14,
    name: "Topografi LiDAR 400HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Kungkilan Bukit Tengkiling",
    locationCity: "Lahat",
    locationProvince: "Sumatera Selatan",
    clientName: "Hakim",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 111888000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 15,
    name: "Topografi LIDAR 700HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Helen, Dasep Ahmadi",
    locationCity: "Belitung",
    locationProvince: "Bangka Belitung",
    clientName: "Dasep Ahmadi",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 165000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 16,
    name: "P60 CHCNAV, AA15 ",
    description: "Penjualan Unit Drone P60 dan AA15",
    type: "Penjualan",
    status: "Negosiasi",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Bintang Delapan Mineral",
    locationCity: "Morowali ",
    locationProvince: "Sulawesi Tengah",
    clientName: "Angga",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 3600000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 17,
    name: "X500 CHCNAV, AA6",
    description: "Penjualan Unit DroneX500 dan AA6",
    type: "Penjualan",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Dinas Perumahan Rakyat, Kab HST",
    locationCity: "Kab. Hulu Sungai Tengah",
    locationProvince: "Kalimantan Selatan",
    clientName: "Aron",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 585000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  }
];

export const progressHistory: ProgressEntry[] = [];

export function getUser(id: number): User | undefined {
  return users.find((u) => u.id === id);
}

export const reminders: Reminder[] = [];

export const reminderSchedules: ReminderSchedule[] = [];

export const comments: ProjectComment[] = [];

export const credentials: Credential[] = [
  {
    userId: 6,
    passwordHash:
      "scrypt$16384$8$1$dad6019acaeff8be525e59be5056931f$66cf33bf9ffaba38ca1da809b94033bd947b988d81472e1c4eb4d5cb62bdf852b5c93b78a5e5b7ccdabc41e9177a95bf3b1ca0d67a7b39cbc21b2e54d00d448d",
    devOnly: true,
  },
];

export const projectDependencies: ProjectDependency[] = [];
