import type {
  AgendaEntry,
  Credential,
  ProjectDependency,
  ProgressEntry,
  Project,
  ProjectTypeInfo,
  ProjectComment,
  Reminder,
  ReminderSchedule,
  User,
} from "./types";

export const users: User[] = [
  {
    id: 1,
    name: "Harir",
    email: "harir@jayasurvey.id",
    avatarUrl: null,
    role: "Project Manager",
    accessLevel: "Admin",
    isActive: true
  },
  {
    id: 2,
    name: "Rika",
    email: "rika@jayasurvey.id",
    avatarUrl: null,
    role: "Project Manager",
    accessLevel: "Manager",
    isActive: true
  },
  {
    id: 3,
    name: "Nurdiyansah",
    email: "nurdiyansah@jayasurvey.id",
    avatarUrl: null,
    role: "Project Manager",
    accessLevel: "Anggota",
    isActive: true
  },
  {
    id: 6,
    name: "Admin Uji",
    email: "admin@jayasurvey.id",
    avatarUrl: null,
    role: "Administrator",
    accessLevel: "Admin",
    isActive: true
  }
];

export const currentUser: User = users[0];

export const projectTypes: ProjectTypeInfo[] = [
  { code: "Penjualan", label: "Penjualan", description: "Pengadaan alat dan solusi ke klien.", sortOrder: 0 },
  { code: "Jasa", label: "Jasa", description: "Pekerjaan survei dan layanan lapangan.", sortOrder: 1 },
  { code: "Training", label: "Training", description: "Pelatihan dan transfer pengetahuan.", sortOrder: 2 },
  { code: "Riset", label: "Riset", description: "Kajian pasar dan pengembangan internal.", sortOrder: 3 },
];

export const projects: Project[] = [
  {
    id: 1,
    name: "Riset Carbon Stock",
    description: "Riset mengenai penggunaan SLAM LiDAR Untuk perhitungan Carbon Stock",
    type: "Riset",
    status: "Berjalan",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "Undip",
    locationCity: "Semarang",
    locationProvince: "Jawa Tengah",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: null,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-30",
    deadline: "2026-09-03",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 2,
    name: "MOU ITERA",
    description: "MOU Terkait riset dan training dengan Teknik Geomatik ITERA",
    type: "Riset",
    status: "Berjalan",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "ITERA",
    locationCity: "Lampung",
    locationProvince: "Lampung",
    clientName: "Ulin",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: null,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-09-07",
    deadline: "2026-09-07",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 3,
    name: "Batas Lahan dan Situasi ",
    description: "Jasa Pengukuran Topografi Batas Lahan dan Situasi Area Komplek Pertamina Zona 4 Prabumulih",
    type: "Jasa",
    status: "Berjalan",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 20,
    clientOrg: "PT Pertamina Zona 4 Prabumulih",
    locationCity: "Prabumulih",
    locationProvince: "Sumatera Selatan",
    clientName: "Ilham habibie",
    clientEmail: "",
    clientPhone: "085210207730",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 152100000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-07-06",
    deadline: "2026-09-06",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 4,
    name: "Topografi LiDAR PLTA  Medan Aceh",
    description: "Topografi Lidar PLTA 440 ha dan 846Ha ",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Saris Geoterra",
    locationCity: "Medan, Aceh",
    locationProvince: "Sumatera Utara",
    clientName: "Saris",
    clientEmail: "",
    clientPhone: "085378676656",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 469021500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 5,
    name: "Topografi LiDAR 9000 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Sriwijaya Tansri Energi",
    locationCity: "Muara Enim",
    locationProvince: "Sumatera Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 2205450000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 6,
    name: "Topografi LiDAR 4500 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Sriwijaya Tansri Energi",
    locationCity: "Muara Enim",
    locationProvince: "Sumatera Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 797850000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 7,
    name: "Topografi LIDAR 2762HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Geoffrey Asia Energy",
    locationCity: "Ketapang, ",
    locationProvince: "Kalimantan Barat",
    clientName: "Candra",
    clientEmail: "",
    clientPhone: "081253652680",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 373735000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 8,
    name: "Topografi LiDAR 1500Ha",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "IBIP",
    locationCity: "Bintan",
    locationProvince: "Kepri",
    clientName: "Zuria Hidayat",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 327616500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 9,
    name: "Topografi LiDAR 7000Ha",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Bhaktiputra Persada Nusantara",
    locationCity: "Morowali Utara",
    locationProvince: "Sulawesi Tengah",
    clientName: "Masdar",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 973969500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 10,
    name: "Topografi Foto Udara",
    description: "Topografi Foto Udara",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Trimata Coal Perkasa",
    locationCity: "Musi Banyuasin",
    locationProvince: "Sumatera Selatan",
    clientName: "Karta Sudarso",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 1131700500,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 11,
    name: "Survei GPR 7 KM",
    description: "Survei GPR",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Sufyan",
    locationCity: "Makassar",
    locationProvince: "Sulawesi Selatan",
    clientName: "",
    clientEmail: "",
    clientPhone: "081356001212",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 140000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 12,
    name: "Survei Stock Opname",
    description: "Survei Stock Opname",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Carsurin",
    locationCity: "Pomala",
    locationProvince: "Sulawesi Tenggara",
    clientName: "",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 50000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 3,
    updatedAt: "2026-08-30"
  },
  {
    id: 13,
    name: "Topografi LiDAR 1500 HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Negosiasi",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Anugerah Jaya Buana",
    locationCity: "LuwuTimur",
    locationProvince: "Sulawesi Selatan",
    clientName: "Masdar",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 420523400,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 14,
    name: "Topografi LiDAR 400HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Kungkilan Bukit Tengkiling",
    locationCity: "Lahat",
    locationProvince: "Sumatera Selatan",
    clientName: "Hakim",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 111888000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 15,
    name: "Topografi LIDAR 700HA",
    description: "Topografi Lidar ",
    type: "Jasa",
    status: "Penawaran",
    priority: "Sedang",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Helen, Dasep Ahmadi",
    locationCity: "Belitung",
    locationProvince: "Bangka Belitung",
    clientName: "Dasep Ahmadi",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 165000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 1,
    updatedAt: "2026-08-30"
  },
  {
    id: 16,
    name: "P60 CHCNAV, AA15 ",
    description: "Penjualan Unit Drone P60 dan AA15",
    type: "Penjualan",
    status: "Negosiasi",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "PT Bintang Delapan Mineral",
    locationCity: "Morowali ",
    locationProvince: "Sulawesi Tengah",
    clientName: "Angga",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 3600000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  },
  {
    id: 17,
    name: "X500 CHCNAV, AA6",
    description: "Penjualan Unit DroneX500 dan AA6",
    type: "Penjualan",
    status: "Penawaran",
    priority: "Tinggi",
    priorityMode: "auto",
    progressPct: 0,
    clientOrg: "Dinas Perumahan Rakyat, Kab HST",
    locationCity: "Kab. Hulu Sungai Tengah",
    locationProvince: "Kalimantan Selatan",
    clientName: "Aron",
    clientEmail: "",
    clientPhone: "",
    clientTier: "Reguler",
    penaltyRisk: "Tidak ada",
    value: 585000000,
    contractNo: "",
    contractDate: null,
    paymentTerm: "Full",
    paymentNote: "",
    taxType: "Non PKP",
    salesFee: null,
    operationalCost: null,
    startDate: "2026-08-01",
    deadline: "2026-09-01",
    ownerId: 2,
    updatedAt: "2026-08-30"
  }
];

export const progressHistory: ProgressEntry[] = [];

/**
 * Agenda tim contoh, pekan 31 Agustus - 6 September 2026.
 *
 * Sengaja melatih keempat jenis kegiatan sekaligus satu agenda yang melintasi
 * pekan, supaya tampilan mingguan dan laporan benar-benar teruji.
 */
export const agenda: AgendaEntry[] = [
  {
    id: 1,
    userId: 1,
    projectId: 1,
    kind: "Lapangan",
    startDate: "2026-08-31",
    endDate: "2026-09-02",
    locationCity: "Semarang",
    locationProvince: "Jawa Tengah",
    note: "Pengambilan data SLAM LiDAR petak utara.",
    createdBy: 1,
    updatedAt: "2026-08-28",
  },
  {
    id: 2,
    userId: 1,
    projectId: null,
    kind: "Kantor",
    startDate: "2026-09-03",
    endDate: "2026-09-04",
    locationCity: "Bandung",
    locationProvince: "Jawa Barat",
    note: "Pengolahan data dan rapat divisi.",
    createdBy: 1,
    updatedAt: "2026-08-28",
  },
  {
    id: 3,
    userId: 2,
    projectId: 3,
    kind: "Perjalanan",
    startDate: "2026-09-01",
    endDate: "2026-09-01",
    locationCity: "Prabumulih",
    locationProvince: "Sumatera Selatan",
    note: "Berangkat ke lokasi, transit Palembang.",
    createdBy: 2,
    updatedAt: "2026-08-29",
  },
  {
    id: 4,
    userId: 2,
    projectId: 3,
    kind: "Lapangan",
    startDate: "2026-09-02",
    endDate: "2026-09-05",
    locationCity: "Prabumulih",
    locationProvince: "Sumatera Selatan",
    note: "Pengukuran batas lahan.",
    createdBy: 2,
    updatedAt: "2026-08-29",
  },
  {
    // Diisikan Manager untuk anggotanya — createdBy sengaja berbeda dari userId.
    id: 5,
    userId: 3,
    projectId: 5,
    kind: "Lapangan",
    startDate: "2026-09-01",
    endDate: "2026-09-04",
    locationCity: "Muara Enim",
    locationProvince: "Sumatera Selatan",
    note: "Akuisisi LiDAR blok selatan.",
    createdBy: 2,
    updatedAt: "2026-08-30",
  },
  {
    // Melintasi pergantian pekan: mulai Minggu, berakhir pekan berikutnya.
    id: 6,
    userId: 3,
    projectId: null,
    kind: "Cuti",
    startDate: "2026-09-06",
    endDate: "2026-09-09",
    locationCity: "",
    locationProvince: "",
    note: "Cuti tahunan.",
    createdBy: 3,
    updatedAt: "2026-08-30",
  },
];

export function getUser(id: number): User | undefined {
  return users.find((u) => u.id === id);
}

export const reminders: Reminder[] = [];

export const reminderSchedules: ReminderSchedule[] = [];

export const comments: ProjectComment[] = [];

/**
 * Kredensial masuk keempat akun.
 *
 * `devOnly: false` — hash ini dibangkitkan khusus untuk instalasi ini, bukan
 * contoh yang beredar di repositori publik, jadi berlaku juga di produksi.
 * Sandi awalnya diserahkan ke admin di luar repo; gantilah lewat halaman
 * Kelola Pengguna, dan hash di bawah akan ikut berubah.
 */
export const credentials: Credential[] = [
  {
    userId: 1,
    passwordHash:
      "scrypt$16384$8$1$dc90ad913c9a6411307e76a3412b67f2$7f0c782fe0b93ff9a8d516dbfff92e68db286804d73a440c89c99ef27b5b0ba9d77c0b67fd5adbbac55f44d1fcf87ae28c40e51e2e1d581ded92a8bd2630569e",
    devOnly: false,
  },
  {
    userId: 2,
    passwordHash:
      "scrypt$16384$8$1$44dfbf5896961e5cf19e78a69601b494$90c140c037b05c237dd9c8f3c920402b6d9350554893cef8cb5c176da175d63dd8dd6a760550e1b98709c54696dda2f27ee6b39b9a2348436b80938d3207a4a4",
    devOnly: false,
  },
  {
    userId: 3,
    passwordHash:
      "scrypt$16384$8$1$e3caa6304378f1944c7c34859b333920$da79f28fff16ead04e5040aa05ff39407011a9a7d0ff4dbae6b4668cb3c5aa6ba94485634764c546cd9ce13df89da3bed185309ae5086936490ddf281824d523",
    devOnly: false,
  },
  {
    userId: 6,
    passwordHash:
      "scrypt$16384$8$1$300444755f305fcee0ecf3d6b357ed04$e87ccfc032882ba24eafca01fe613c5a0cb8690b194d5fb54b596df5543772e74ceac10fdbed506b83625efa49b868b8f6707d3965c2234a91fae9908d51b88a",
    devOnly: false,
  },
];

export const projectDependencies: ProjectDependency[] = [];
